# ICD Suggest & Specifier Tray - Docker Development Setup
# This file sets up the development environment with one command
# Run: docker-compose up

version: "3.9"

services:
  # Backend API server
  api:
    build: 
      context: ../apps/api
      dockerfile: Dockerfile
    env_file: 
      - ../.env
    ports: 
      - "3000:3000"
    depends_on: []
    volumes:
      # Mount source code for hot reloading during development
      - ../apps/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  # Frontend web application
  web:
    build: 
      context: ../apps/web
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
    volumes:
      # Mount source code for hot reloading during development
      - ../apps/web:/app
      - /app/node_modules
    environment:
      # Point frontend to backend API
      - VITE_API_BASE=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - api
    restart: unless-stopped

# =============================================================================
# USAGE INSTRUCTIONS
# =============================================================================
#
# 1. Copy env.example to .env and fill in your database URL
# 2. Run: docker-compose up
# 3. Frontend will be available at: http://localhost:5173
# 4. Backend API will be available at: http://localhost:3000
#
# For development with hot reloading:
# - Frontend changes will auto-reload
# - Backend changes will auto-restart
#
# To stop: docker-compose down
# To rebuild: docker-compose up --build
#

